name: Build and Release

on:
  push:
    tags: 
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: |
        pip install build
        python -m build --wheel
    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.whl